In [ ]:
import pandas as pd
df = pd.read_csv('/content/Bengaluru_House_Data.csv')

In [ ]:
df.head()

              area_type   availability  ... balcony   price
0  Super built-up  Area         19-Dec  ...     1.0   39.07
1            Plot  Area  Ready To Move  ...     3.0  120.00
2        Built-up  Area  Ready To Move  ...     3.0   62.00
3  Super built-up  Area  Ready To Move  ...     1.0   95.00
4  Super built-up  Area  Ready To Move  ...     1.0   51.00

[5 rows x 9 columns]

In [ ]:
df.dtypes

area_type        object
availability     object
location         object
size             object
society          object
total_sqft       object
bath            float64
balcony         float64
price           float64
dtype: object

In [ ]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [ ]:
df['area_type'].value_counts()

Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: area_type, dtype: int64

In [ ]:
df['availability'].value_counts()

Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Jun               1
17-Jan               1
16-Jul               1
14-Nov               1
14-Jul               1
Name: availability, Length: 81, dtype: int64

In [ ]:
df = df.drop(['availability','society'],axis=1)

In [ ]:
df.head()

              area_type                  location  ... balcony   price
0  Super built-up  Area  Electronic City Phase II  ...     1.0   39.07
1            Plot  Area          Chikka Tirupathi  ...     3.0  120.00
2        Built-up  Area               Uttarahalli  ...     3.0   62.00
3  Super built-up  Area        Lingadheeranahalli  ...     1.0   95.00
4  Super built-up  Area                  Kothanur  ...     1.0   51.00

[5 rows x 7 columns]

In [ ]:
k = '5 Bedroom'
int(k.split(' ')[0])

5

In [ ]:
df.isnull().sum()

area_type       0
location        1
size           16
total_sqft      0
bath           73
balcony       609
price           0
dtype: int64

In [ ]:
df.shape

(13320, 7)

In [ ]:
df = df.dropna()

In [ ]:
df.shape

(12710, 7)

In [ ]:
def bhk(x):
  return int(x.split(' ')[0])

In [ ]:
df['size'] = df['size'].apply(bhk)

In [ ]:
df.head()

              area_type                  location  size  ... bath  balcony   price
0  Super built-up  Area  Electronic City Phase II     2  ...  2.0      1.0   39.07
1            Plot  Area          Chikka Tirupathi     4  ...  5.0      3.0  120.00
2        Built-up  Area               Uttarahalli     3  ...  2.0      3.0   62.00
3  Super built-up  Area        Lingadheeranahalli     3  ...  3.0      1.0   95.00
4  Super built-up  Area                  Kothanur     2  ...  2.0      1.0   51.00

[5 rows x 7 columns]

In [ ]:
df.dtypes

area_type      object
location       object
size            int64
total_sqft     object
bath          float64
balcony       float64
price         float64
dtype: object

In [ ]:
def average(x):
  try:
    if len(x.split('-')) == 2:
      return (float(x.split('-')[0]) + float(x.split('-')[1]))/2
    else:
      return float(x)
  except:
    return None

In [ ]:
df['total_sqft'] = df['total_sqft'].apply(average)

In [ ]:
df.isnull().sum()

area_type      0
location       0
size           0
total_sqft    42
bath           0
balcony        0
price          0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df.dtypes

area_type      object
location       object
size            int64
total_sqft    float64
bath          float64
balcony       float64
price         float64
dtype: object

In [ ]:
df.isnull().sum()

area_type     0
location      0
size          0
total_sqft    0
bath          0
balcony       0
price         0
dtype: int64

In [ ]:
df.head()

              area_type                  location  size  ...  bath  balcony   price
0  Super built-up  Area  Electronic City Phase II     2  ...   2.0      1.0   39.07
1            Plot  Area          Chikka Tirupathi     4  ...   5.0      3.0  120.00
2        Built-up  Area               Uttarahalli     3  ...   2.0      3.0   62.00
3  Super built-up  Area        Lingadheeranahalli     3  ...   3.0      1.0   95.00
4  Super built-up  Area                  Kothanur     2  ...   2.0      1.0   51.00

[5 rows x 7 columns]

In [ ]:
df2 = df.drop('area_type',axis=1)

In [ ]:
df2.head()

                   location  size  total_sqft  bath  balcony   price
0  Electronic City Phase II     2      1056.0   2.0      1.0   39.07
1          Chikka Tirupathi     4      2600.0   5.0      3.0  120.00
2               Uttarahalli     3      1440.0   2.0      3.0   62.00
3        Lingadheeranahalli     3      1521.0   3.0      1.0   95.00
4                  Kothanur     2      1200.0   2.0      1.0   51.00

In [ ]:
len(df2['location'].unique())

1259

In [ ]:
prop_count = df2['location'].value_counts()

In [ ]:
more_then_20 = prop_count[prop_count > 20]

In [ ]:
less_then_20 = prop_count[prop_count <= 20]

In [ ]:
def location_update(x):
  if x in more_then_20:
    return x
  else:
    'Others'

In [ ]:
df2['location'] = df2['location'].apply(location_update)

In [ ]:
len(df2['location'].unique())

139

In [ ]:
dfl = pd.get_dummies(df2['location'])

In [ ]:
df3 = pd.concat((df2,dfl),axis=1)

In [ ]:
df3.head()

                   location  size  ...  Yelahanka New Town  Yeshwanthpur
0  Electronic City Phase II     2  ...                   0             0
1                      None     4  ...                   0             0
2               Uttarahalli     3  ...                   0             0
3        Lingadheeranahalli     3  ...                   0             0
4                  Kothanur     2  ...                   0             0

[5 rows x 144 columns]

In [ ]:
#df4 = df3.drop('location',axis=1)

In [ ]:
df3.head()

                   location  size  ...  Yelahanka New Town  Yeshwanthpur
0  Electronic City Phase II     2  ...                   0             0
1                      None     4  ...                   0             0
2               Uttarahalli     3  ...                   0             0
3        Lingadheeranahalli     3  ...                   0             0
4                  Kothanur     2  ...                   0             0

[5 rows x 144 columns]

#Outliers removal

In [ ]:
df3['size'].unique()

NameError: ignored

In [ ]:
df5 = df3[(df3['total_sqft'] / df3['size']) > 300]

In [ ]:
df5['size'].unique()

In [ ]:
df5['bath'].unique()

In [ ]:
df5.shape

In [ ]:
df6 = df5[df5['bath'] <= df5['size'] + 2]

In [ ]:
df6['bath'].unique()

In [ ]:
df6.shape

In [ ]:
df6.insert(5,'PPS',(df6['price'] * 100000) /df6['total_sqft'])

In [ ]:
df6.head()

In [ ]:
df6['PPS'].describe()

In [ ]:
df6.groupby('location')['PPS'].mean()

In [ ]:
df6.groupby('location')['PPS'].max()

In [ ]:
df6.groupby('location')['PPS'].min()

In [ ]:
for key,dfloc in df6.groupby('location'):
  print(dfloc)

In [ ]:
df6.shape

In [ ]:
df7 = pd.DataFrame()
for key,dfloc in df6.groupby('location'):
  m = dfloc['PPS'].mean()
  s = dfloc['PPS'].std()

  extracted_df = dfloc[(dfloc['PPS'] > (m-2*s)) & (dfloc['PPS'] < (m+2*s))]
  df7 = pd.concat([df7,extracted_df],ignore_index=True)

In [ ]:
df7.head()

In [ ]:
df8 = df7.drop(['location','PPS'],axis=1)

In [ ]:
df8

In [ ]:
X = df8.drop('price',axis=1)
Y = df8[['price']]

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,train_size=0.8)

In [ ]:
from sklearn.linear_model import LinearRegression
lmodel = LinearRegression()

lmodel.fit(xtrain,ytrain)

In [ ]:
ytrain_pred = lmodel.predict(xtrain)
ytest_pred = lmodel.predict(xtest)

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print(mean_absolute_error(ytrain,ytrain_pred))
print(mean_absolute_error(ytest,ytest_pred))

In [ ]:
ytest['price'].min()

In [ ]:
ytest['price'].max()

In [ ]:
ytest['price'].mean()

In [ ]:
len(xtrain.columns)

In [ ]:
xtrain.columns

In [ ]:
import numpy as np
def predict_price(size,sqft,bath,balcony,location):
  input = np.zeros(len(xtrain.columns))
  input[0] = size
  input[1] = sqft
  input[2] = bath
  input[3] = balcony

  loc = np.where(xtrain.columns == location)
  input[loc] = 1

  return lmodel.predict([input])

In [ ]:
print(predict_price(3,1750,2,4,'Whitefield'))