In [1]:
dataset = [['Milk','Onion','Nutmeg','Kidney Beans','Eggs','Yogurt'],
           ['Dill','Onion','Nutmeg','Kidney Beans','Eggs','Yogurt'],
           ['Milk','Apple','Kidney Beans','Eggs'],
           ['Milk','Unicorn','Corn','Kidney Beans','Yogurt'],
           ['Corn','Onion','Onion','Kidney Beans','Ice cream','Eggs']]
print(dataset)

[['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'], ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'], ['Milk', 'Apple', 'Kidney Beans', 'Eggs'], ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'], ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

In [3]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)

In [4]:
df = pd.DataFrame(te_ary,columns=te.columns_)
df

   Apple   Corn   Dill   Eggs  Ice cream  ...   Milk  Nutmeg  Onion  Unicorn  Yogurt
0  False  False  False   True      False  ...   True    True   True    False    True
1  False  False   True   True      False  ...  False    True   True    False    True
2   True  False  False   True      False  ...   True   False  False    False   False
3  False   True  False  False      False  ...   True   False  False     True    True
4  False   True  False   True       True  ...  False   False   True    False   False

[5 rows x 11 columns]

In [5]:
from mlxtend.frequent_patterns import apriori
frequent_itemsets = apriori(df,use_colnames=True,min_support=0.6)
frequent_itemsets

    support                     itemsets
0       0.8                       (Eggs)
1       1.0               (Kidney Beans)
2       0.6                       (Milk)
3       0.6                      (Onion)
4       0.6                     (Yogurt)
5       0.8         (Kidney Beans, Eggs)
6       0.6                (Onion, Eggs)
7       0.6         (Milk, Kidney Beans)
8       0.6        (Onion, Kidney Beans)
9       0.6       (Yogurt, Kidney Beans)
10      0.6  (Kidney Beans, Onion, Eggs)

#Association Rule mining

In [6]:
from mlxtend.frequent_patterns import association_rules
res = association_rules(frequent_itemsets,metric='support',min_threshold=0.5)
res

              antecedents            consequents  ...  leverage  conviction
0          (Kidney Beans)                 (Eggs)  ...      0.00         1.0
1                  (Eggs)         (Kidney Beans)  ...      0.00         inf
2                 (Onion)                 (Eggs)  ...      0.12         inf
3                  (Eggs)                (Onion)  ...      0.12         1.6
4                  (Milk)         (Kidney Beans)  ...      0.00         inf
5          (Kidney Beans)                 (Milk)  ...      0.00         1.0
6                 (Onion)         (Kidney Beans)  ...      0.00         inf
7          (Kidney Beans)                (Onion)  ...      0.00         1.0
8                (Yogurt)         (Kidney Beans)  ...      0.00         inf
9          (Kidney Beans)               (Yogurt)  ...      0.00         1.0
10  (Onion, Kidney Beans)                 (Eggs)  ...      0.12         inf
11   (Eggs, Kidney Beans)                (Onion)  ...      0.12         1.6
12          (Onion, Eggs)         (Kidney Beans)  ...      0.00         inf
13         (Kidney Beans)          (Onion, Eggs)  ...      0.00         1.0
14                (Onion)   (Eggs, Kidney Beans)  ...      0.12         inf
15                 (Eggs)  (Onion, Kidney Beans)  ...      0.12         1.6

[16 rows x 9 columns]

In [7]:
res1 = res[['antecedents','consequents','support','confidence','lift']]
res1

              antecedents            consequents  support  confidence  lift
0          (Kidney Beans)                 (Eggs)      0.8        0.80  1.00
1                  (Eggs)         (Kidney Beans)      0.8        1.00  1.00
2                 (Onion)                 (Eggs)      0.6        1.00  1.25
3                  (Eggs)                (Onion)      0.6        0.75  1.25
4                  (Milk)         (Kidney Beans)      0.6        1.00  1.00
5          (Kidney Beans)                 (Milk)      0.6        0.60  1.00
6                 (Onion)         (Kidney Beans)      0.6        1.00  1.00
7          (Kidney Beans)                (Onion)      0.6        0.60  1.00
8                (Yogurt)         (Kidney Beans)      0.6        1.00  1.00
9          (Kidney Beans)               (Yogurt)      0.6        0.60  1.00
10  (Onion, Kidney Beans)                 (Eggs)      0.6        1.00  1.25
11   (Eggs, Kidney Beans)                (Onion)      0.6        0.75  1.25
12          (Onion, Eggs)         (Kidney Beans)      0.6        1.00  1.00
13         (Kidney Beans)          (Onion, Eggs)      0.6        0.60  1.00
14                (Onion)   (Eggs, Kidney Beans)      0.6        1.00  1.25
15                 (Eggs)  (Onion, Kidney Beans)      0.6        0.75  1.25

In [8]:
res1[res1['confidence'] >= 1]

              antecedents           consequents  support  confidence  lift
1                  (Eggs)        (Kidney Beans)      0.8         1.0  1.00
2                 (Onion)                (Eggs)      0.6         1.0  1.25
4                  (Milk)        (Kidney Beans)      0.6         1.0  1.00
6                 (Onion)        (Kidney Beans)      0.6         1.0  1.00
8                (Yogurt)        (Kidney Beans)      0.6         1.0  1.00
10  (Onion, Kidney Beans)                (Eggs)      0.6         1.0  1.25
12          (Onion, Eggs)        (Kidney Beans)      0.6         1.0  1.00
14                (Onion)  (Eggs, Kidney Beans)      0.6         1.0  1.25